### ISSUE TITLE
Pterodactyl requires a new template for the cron worker

### ISSUE THREAD

**Issue by Maelstromeous** [ibracorp/unraid-templates#3]
Hello,

First of all thanks for bringing these templates to the unraid community! However there is a slight issue that's occuring with the panel one, the feature called "scheules" (which is basically cron) doesn't work with your template.

By default the panel container executes a command called `p:start`, this only however starts the panel and associated services. What is required as another container than acts as the cron worker. Essentially the template would be the same, however there needs to be some way to trigger the entrypoint to trigger `p:cron` instead of it's current default, `p:start`.

**Comment by ibracorp-sycotix** [comment]
Any chance of a PR for this?

**Comment by Maelstromeous** [comment]
I could certainly try to get one going but I'm not massively familiar with the unfair development flow, would have thought this would be fairly simple to achieve?

**Comment by jjbrunton** [comment]
Has anyone resolved this? Schedules do not work on this image.

**Comment by ibracorp-sycotix** [comment]
We see what the problem is but don't know the solution. If anyone would like to submit a PR please do so and we'd be happy to merge. Only two of us are managing everything at this time. 

Thanks
