### ISSUE TITLE
plex-wrapped changed repositories

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [ibracorp/unraid-templates#4]
The plex-wrapped author changed the name of the project and therefore the dockerhub URL, so it is no longer pull-able from Unraid CA via the template your team created.

New project:

https://github.com/aunefyren/wrapperr

https://hub.docker.com/r/aunefyren/wrapperr

**Comment by ibracorp-sycotix** [comment]
Fixed shortly after this was created, thanks!
